"""add post status published at constraint

Revision ID: 08f012f379fa
Revises: c0f16c9072bf
Create Date: 2026-08-30 21:45:37.136136

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08f012f379fa"
down_revision: str | Sequence[str] | None = "c0f16c9072bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("ck_posts_status_published_at_consistency"),
        "posts",
        """
        (status = 'draft' AND published_at IS NULL)
        OR
        (
            status IN ('published', 'archived')
            AND published_at IS NOT NULL
        )
        """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_posts_status_published_at_consistency"),
        "posts",
        type_="check",
    )
    # ### end Alembic commands ###
