"""add bookmarks

Revision ID: 556e54fa4471
Revises: befd9132da40
Create Date: 2026-09-03 01:20:07.098124

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "556e54fa4471"
down_revision: str | Sequence[str] | None = "befd9132da40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookmarks",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("saved_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], name=op.f("fk_bookmarks_post_id_posts"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_bookmarks_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "post_id", name=op.f("pk_bookmarks")),
    )
    op.create_index("ix_bookmarks_post_id", "bookmarks", ["post_id"], unique=False)
    op.create_index(
        "ix_bookmarks_user_id_saved_at_post_id",
        "bookmarks",
        ["user_id", sa.literal_column("saved_at DESC"), sa.literal_column("post_id DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bookmarks_user_id_saved_at_post_id", table_name="bookmarks")
    op.drop_index("ix_bookmarks_post_id", table_name="bookmarks")
    op.drop_table("bookmarks")
    # ### end Alembic commands ###
