"""align post indexes and reset token constraints

Revision ID: 6ab965a8af94
Revises: abba6e0f892a
Create Date: 2026-06-26 01:34:23.226258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab965a8af94'
down_revision: Union[str, Sequence[str], None] = 'abba6e0f892a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.create_unique_constraint('uq_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'])
    op.drop_index(op.f('ix_posts_user_id_created_at'), table_name='posts')
    op.create_index('ix_posts_created_at_id', 'posts', [sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('ix_posts_user_id_created_at_id', 'posts', ['user_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_user_id_created_at_id', table_name='posts')
    op.drop_index('ix_posts_created_at_id', table_name='posts')
    op.create_index(op.f('ix_posts_user_id_created_at'), 'posts', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_constraint('uq_password_reset_tokens_user_id', 'password_reset_tokens', type_='unique')
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###
