"""add post status and published at

Revision ID: c0f16c9072bf
Revises: 5341a4520f42
Create Date: 2026-08-27 23:10:16.849493

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0f16c9072bf"
down_revision: str | Sequence[str] | None = "5341a4520f42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "status",
            sa.Enum("draft", "published", "archived", name="post_status", native_enum=False, create_constraint=True),
            server_default="draft",
            nullable=False,
        ),
    )
    op.add_column("posts", sa.Column("published_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        "ix_posts_status_published_at_id",
        "posts",
        ["status", sa.literal_column("published_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_posts_status_published_at_id", table_name="posts")
    op.drop_column("posts", "published_at")
    op.drop_column("posts", "status")
    # ### end Alembic commands ###
