"""add posts_updated_at_id index

Revision ID: dd9cff3b2c2a
Revises: 11e0bae3a19e
Create Date: 2026-08-20 18:02:38.097671

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd9cff3b2c2a"
down_revision: str | Sequence[str] | None = "11e0bae3a19e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_posts_updated_at_id",
        "posts",
        [sa.literal_column("updated_at DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_posts_updated_at_id", table_name="posts")
    # ### end Alembic commands ###
