"""add follows

Revision ID: ddc9fd17dc26
Revises: 556e54fa4471
Create Date: 2026-09-03 21:21:18.555351

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ddc9fd17dc26"
down_revision: str | Sequence[str] | None = "556e54fa4471"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follows",
        sa.Column("follower_id", sa.Uuid(), nullable=False),
        sa.Column("followed_user_id", sa.Uuid(), nullable=False),
        sa.Column("followed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "\n            follower_id <> followed_user_id\n            ", name=op.f("ck_follows_no_self_follow")
        ),
        sa.ForeignKeyConstraint(
            ["followed_user_id"], ["users.id"], name=op.f("fk_follows_followed_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"], ["users.id"], name=op.f("fk_follows_follower_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("follower_id", "followed_user_id", name=op.f("pk_follows")),
    )
    op.create_index(
        "ix_follows_followed_user_created_at_follower",
        "follows",
        ["followed_user_id", sa.literal_column("followed_at DESC"), sa.literal_column("follower_id DESC")],
        unique=False,
    )
    op.create_index(
        "ix_follows_follower_created_at_followed_user",
        "follows",
        ["follower_id", sa.literal_column("followed_at DESC"), sa.literal_column("followed_user_id DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_follows_follower_created_at_followed_user", table_name="follows")
    op.drop_index("ix_follows_followed_user_created_at_follower", table_name="follows")
    op.drop_table("follows")
    # ### end Alembic commands ###
